@base_url = http://web.fc.utm.my/ttms
@url = {{base_url}}/web_man_webservice_json.cgi?
@username = 12085
@password = S808323
@session = 31754207169943
@session_admin = 668335569336344
@sesi = 2023/2024
@semester = 2
### Login
GET {{url}}entity=authentication&login={{username}}&password={{password}}
### Admin Login
GET {{base_url}}/auth-admin.php?session_id={{session}}



### sesisemester
GET {{url}}entity=sesisemester HTTP/1.1

### subjek
GET {{url}}entity=subjek&sesi={{sesi}}&semester={{semester}} HTTP/1.1

### pensyarah
GET {{url}}entity=pensyarah&session_id={{session_admin}}&sesi=2023/2024&semester=2

### pelajar (Max = 100)
GET {{url}}entity=pelajar&session_id={{session_admin}}&sesi={{sesi}}&semester={{semester}}&limit=100&offset=3500

### pensyarah_subjek (Dr Zalmiyah)
GET {{url}}entity=pensyarah_subjek&no_pekerja=15606
###
GET {{url}}entity=pensyarah_subjek&no_pekerja=30744

### pelajar_subjek (CYK)
GET {{url}}entity=pelajar_subjek&no_matrik=A20EC0185

### subjek_seksyen - List of Course(Section List)
GET {{url}}entity=subjek_seksyen&sesi={{sesi}}&semester={{semester}}

### subjek_pelajar (Advanced AI) - List of Student by Subject & Section
GET {{url}}entity=subjek_pelajar&session_id={{session_admin}}&sesi={{sesi}}&semester={{semester}}&kod_subjek=SECJ5043&seksyen=1

### subjek_pensyarah - Lecturer by Subject & Section
GET {{url}}entity=subjek_pensyarah&sesi={{sesi}}&semester={{semester}}&kod_subjek=SECJ5043&seksyen=1